### ISSUE TITLE
Foreign key constraint on many to many relation

### ISSUE THREAD

**Issue by maches** [nelmio/alice#746]
Hi,
I have an error when I try to add elements to many-to-many relation.
There are fixtures:
```yaml
AppBundle\Entity\Subject:
    subjectTemp (template):
        createdAt: <dateTimeBetween("-5 days", "now")>
        updatedAt: <dateTimeBetween($createdAt, "now")>
    subject{1..9} (extends subjectTemp):
        name: '<subject_name(<current()>)>'

AppBundle\Entity\Activity:
    activityTemp (template):
        createdAt: <dateTimeBetween("-5 days", "now")>
        updatedAt: <dateTimeBetween($createdAt, "now")>
        executionControl: '85%? @control1 : @control2'
        shortDescription: '<realText(150)>'
        fullDescription: '<realText(1500)>'
        isImportant: '10%? 1 : 0'
        isOnline: '35%? 1 : 0'
        region: '@region_*'
        activityType: '@type*'
        subjects: '3x @subject*'
    activity{1..15} (extends activityTemp):
        name: 'Activity <current()>'
```
And error:
 ```
Integrity constraint violation: 1062 Duplicate entry '251-230' for key 'PRIMARY' 
```
I tried to solve this problem with (unique), but got another error. It's about 150 attempts.
Am I miss something? How I can solve this? 
Thanks.

**Comment by theofidry** [comment]
Hi,

I think the error error is rather straight-forward: you have two objects with the same ID. So which entity and what are the values supposed to be I can't guess, but I think you'll have the answer by inspecting the generated objects to see if they match what you expected.

Also the `(unique)` doesn't work for arrays in 2.x (fixed in 3.x)

**Comment by maches** [comment]
@theofidry, thank you for your help! 
I use 3.0.0-RC.0.
I expected that adding more than one object would not duplicate the existing ones in this array. I assume that there are duplicates among the added objects. Is it possible?
I will try to get as much information as possible and let you know.

**Comment by maches** [comment]
```
array(3) {
  [0] =>
  class AppBundle\Entity\Subject#4246 (5) {
    private $id =>
    NULL
    private $name =>
    string(31) "Иностранный язык"
    private $createdAt =>
    class DateTime#2717 (3) {
      public $date =>
      string(26) "2017-06-02 20:53:27.000000"
      public $timezone_type =>
      int(3)
      public $timezone =>
      string(13) "Europe/Moscow"
    }
    private $updatedAt =>
    class DateTime#2623 (3) {
      public $date =>
      string(26) "2017-06-03 07:22:45.000000"
      public $timezone_type =>
      int(3)
      public $timezone =>
      string(13) "Europe/Moscow"
    }
    private $activities =>
    class Doctrine\Common\Collections\ArrayCollection#3161 (1) {
      private $elements =>
      array(0) {
        ...
      }
    }
  }
  [1] =>
  class AppBundle\Entity\Subject#3407 (5) {
    private $id =>
    NULL
    private $name =>
    string(22) "Информатика"
    private $createdAt =>
    class DateTime#2407 (3) {
      public $date =>
      string(26) "2017-06-03 15:48:10.000000"
      public $timezone_type =>
      int(3)
      public $timezone =>
      string(13) "Europe/Moscow"
    }
    private $updatedAt =>
    class DateTime#2375 (3) {
      public $date =>
      string(26) "2017-06-05 23:03:18.000000"
      public $timezone_type =>
      int(3)
      public $timezone =>
      string(13) "Europe/Moscow"
    }
    private $activities =>
    class Doctrine\Common\Collections\ArrayCollection#3439 (1) {
      private $elements =>
      array(0) {
        ...
      }
    }
  }
  [2] =>
  class AppBundle\Entity\Subject#4246 (5) {
    private $id =>
    NULL
    private $name =>
    string(31) "Иностранный язык"
    private $createdAt =>
    class DateTime#2717 (3) {
      public $date =>
      string(26) "2017-06-02 20:53:27.000000"
      public $timezone_type =>
      int(3)
      public $timezone =>
      string(13) "Europe/Moscow"
    }
    private $updatedAt =>
    class DateTime#2623 (3) {
      public $date =>
      string(26) "2017-06-03 07:22:45.000000"
      public $timezone_type =>
      int(3)
      public $timezone =>
      string(13) "Europe/Moscow"
    }
    private $activities =>
    class Doctrine\Common\Collections\ArrayCollection#3161 (1) {
      private $elements =>
      array(0) {
        ...
      }
    }
```
First and last element are equal. Is this normal?

**Comment by theofidry** [comment]
@maches I don't know how your `subject_name()` method works but one problem seems to come from there as it looks like it returns multiple time the same value.

However it's unlikely to be the root of the issue has your issue comes from a duplicate primary key. Check which entity is causing this and if it's not simply because the database is not purged correctly  between each tests

**Comment by maches** [comment]
@theofidry Thanks! That's it!
 I use custom Faker provider for names which return value by `current()` index.

 I expected that the elements would not be duplicated, but it's not. Is this described in the documentation? I don't remember, but IMHO should be added, if it is not.

 I think that using the built-in function `sentence()` will solve this problem, or I can filter the repeated elements in the `setSubject` method. Filtering will reduce the number of elements, but this is even useful to me.

 On the other hand, maintaining this `set` methods for relations is a strange solution for the sake of realistic data. The choice is mine. Thank you!

**Comment by maches** [comment]
@theofidry `sentence` won't help. Database always clear before flush. Prblem still actual.

**Comment by theofidry** [comment]
>I expected that the elements would not be duplicated

Which one are you talking about? `<current()>` in your case will return `0`, `1`, ..`9`. A Faker provider can perfectly return duplicate data and if you don't want that you have to force `unique`.

So the issue is duplicate entities for `subjects`? If so `unique` solves the problem, but as you have 9 subjects for 15 activities and each activities requires 3 subjects, you won't have enough subjects...

**Comment by maches** [comment]
Subjects: [ Mathematics, Informatics, Mathematics ]  This example show the root of problem. Unique will not help. I have a 100+ activities on test server with quantity of subjects from 0 to 3 (someone have relation with all subjects). And there are no problems with the keys.

**Comment by theofidry** [comment]
>because It's a valid unique value of array

That is true only in 2.x, this has been fixed in 3.x. If you really need that and can't upgrade I recommend you to rely on a custom Faker provider: you pass it all the subjects and it does its own thing to get 3 unique subjects at each call

**Comment by maches** [comment]
@theofidry , great idea! I will definitely try the proposed solution! I just need to figure out how to get all the generated subjects inside Faker provider. Thanks!

**Comment by maches** [comment]
@theofidry I use 3.0.0-RC.0. When I try to use a unique, I get a huge error log. Then I increment verbosity to -vvv and get huge log and this trace after it. Maybe it helps.

```
Exception trace:
 () at /home/maches/www/itmo.start/vendor/theofidry/alice-data-fixtures/src/Exception/MaxPassReachedException.php:60
 Fidry\AliceDataFixtures\Exception\MaxPassReachedException::createForLimit() at /home/maches/www/itmo.start/vendor/theofidry/alice-data-fixtures/src/Loader/MultiPassLoader.php:87
 Fidry\AliceDataFixtures\Loader\MultiPassLoader->load() at /home/maches/www/itmo.start/var/cache/dev/appDevDebugProjectContainer.php:9179
 FidryAliceDataFixturesLoaderMultiPassLoader_00000000474511e5000000000e41a4ef51400951f92b145c5ab5fc88d4c2d008->load() at /home/maches/www/itmo.start/vendor/theofidry/alice-data-fixtures/src/Loader/PersisterLoader.php:76
 Fidry\AliceDataFixtures\Loader\PersisterLoader->load() at /home/maches/www/itmo.start/vendor/theofidry/alice-data-fixtures/src/Loader/PurgerLoader.php:67
 Fidry\AliceDataFixtures\Loader\PurgerLoader->load() at /home/maches/www/itmo.start/vendor/theofidry/alice-data-fixtures/src/Loader/FileResolverLoader.php:56
 Fidry\AliceDataFixtures\Loader\FileResolverLoader->load() at /home/maches/www/itmo.start/vendor/hautelook/alice-bundle/src/Loader/DoctrineOrmLoader.php:172
 Hautelook\AliceBundle\Loader\DoctrineOrmLoader->loadFixtures() at /home/maches/www/itmo.start/vendor/hautelook/alice-bundle/src/Loader/DoctrineOrmLoader.php:104
 Hautelook\AliceBundle\Loader\DoctrineOrmLoader->load() at /home/maches/www/itmo.start/vendor/hautelook/alice-bundle/src/Console/Command/Doctrine/DoctrineOrmLoadDataFixturesCommand.php:139
 Hautelook\AliceBundle\Console\Command\Doctrine\DoctrineOrmLoadDataFixturesCommand->execute() at /home/maches/www/itmo.start/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /home/maches/www/itmo.start/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:854
 Symfony\Component\Console\Application->doRunCommand() at /home/maches/www/itmo.start/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:201
 Symfony\Component\Console\Application->doRun() at /home/maches/www/itmo.start/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:81
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/maches/www/itmo.start/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:125
 Symfony\Component\Console\Application->run() at /home/maches/www/itmo.start/bin/console:28
```

Here are some messages about exceptions from a huge log without a stack trace. They are repeated many times.
```
Next Nelmio\Alice\Throwable\Exception\Generator\Resolver\UnresolvableValueDuringGenerationException: Could not resolve value during the generation process. in /home/maches/www/itmo.start/vendor/nelmio/alice/src/Throwable/Ex  
  ception/Generator/Resolver/UnresolvableValueDuringGenerationExceptionFactory.php:25 


 Nelmio\Alice\Throwable\Exception\Generator\Resolver\UniqueValueGenerationLimitReachedException: Could not generate a unique value after 150 attempts for "AppBundle\Entity\Activity#subjects::593709508eeb22.94289414". in /  
  home/maches/www/itmo.start/vendor/nelmio/alice/src/Throwable/Exception/Generator/Resolver/UniqueValueGenerationLimitReachedExceptionFactory.php:25      
```
So the `unique` doesn't solve my problem. And this is 3.x version!

**Comment by theofidry** [comment]
You should try to debug with xdebug by marking a break point to inspect things when just before `UniqueValueGenerationLimitReachedExceptionFactory` is called, it will give you hints as why no unique value could be generated

**Comment by theofidry** [comment]
Closing as it's an issue in the consumer code, not alice :)
